version: "3.8"

services:
  backend-agility:
    build: ./backend/docker
    container_name: backend-agility
    restart: unless-stopped
    command: wait-for db-agility-mysql:3306 -t 40 -- ./docker/start.sh
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/home/php/backend
    depends_on:
      - db-agility-mysql
    networks:
      - network-agility

  db-agility-mysql:
    image: mysql:8.0
    container_name: db-agility-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=agility
      - MYSQL_USER=agilityTest
      - MYSQL_ROOT_PASSWORD=mypassword
    volumes:
      - ./dbData:/var/lib/mysql
    networks:
      - network-agility

networks:
  network-agility:
    driver: bridge
